// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIMeqP4-skuR7awzr8Ma-qRSSAOXWwzTY',
    appId: '1:716916885518:web:7b14ddf016fdb4ae7bd45f',
    messagingSenderId: '716916885518',
    projectId: 'cs-4361',
    authDomain: 'cs-4361.firebaseapp.com',
    storageBucket: 'cs-4361.appspot.com',
    measurementId: 'G-ZLD2W0EBY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjt-gI4Uf2EUL-0qsSqsTyXCPbjCdjAP8',
    appId: '1:716916885518:android:f7c71158316ab5ff7bd45f',
    messagingSenderId: '716916885518',
    projectId: 'cs-4361',
    storageBucket: 'cs-4361.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvfuGlwb0mWAlZhZFUd5QtsNXvdJFzlBo',
    appId: '1:716916885518:ios:ca9435eacef926487bd45f',
    messagingSenderId: '716916885518',
    projectId: 'cs-4361',
    storageBucket: 'cs-4361.appspot.com',
    iosBundleId: 'com.healersoft.cs4361',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvfuGlwb0mWAlZhZFUd5QtsNXvdJFzlBo',
    appId: '1:716916885518:ios:2a28bb28501b09c17bd45f',
    messagingSenderId: '716916885518',
    projectId: 'cs-4361',
    storageBucket: 'cs-4361.appspot.com',
    iosBundleId: 'com.healersoft.cs4361.RunnerTests',
  );
}
